CLS
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
INPUT "Choose number of times to hear song.  If you want to cut short,                 then press Shift + Pause (Break). Now, number of times wanted"; Y
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
FOR X = 1 TO Y
PRINT "go..."
PLAY "t120o1l16b9n0baan0bn0bn0baaan0b9n0baan0b"
PRINT "GO..."
PLAY "o2l16e-9n0e-d-d-n0e-n0e-n0e-d-d-d-n0e-9n0e-d-d-n0e-"
PRINT "GO!"
PLAY "o2l16g-9n0g-een0g-n0g-n0g-eeen0g-9n0g-een0g-"
PRINT "  GGGGGGGGGG          OOOOOOOOOO        !!!!"
PRINT "  GGGGGGGGGG          OOOOOOOOOO        !!!!"
PRINT "GGGG      GGGG      OOOO      OOOO      !!!!"
PRINT "GGGG      GGGG      OOOO      OOOO      !!!!"
PRINT "GGGG                OOOO      OOOO      !!!!"
PRINT "GGGG                OOOO      OOOO      !!!!"
PRINT "GGGG    GGGGGG      OOOO      OOOO      !!!!"
PRINT "GGGG    GGGGGG      OOOO      OOOO      !!!!"
PRINT "GGGG      GGGG      OOOO      OOOO      !!!!"
PRINT "GGGG      GGGG      OOOO      OOOO      !!!!"
PRINT "GGGG      GGGG      OOOO      OOOO"
PRINT "GGGG      GGGG      OOOO      OOOO"
PRINT "  GGGGGGGGGG          OOOOOOOOOO        !!!!"
PRINT "  GGGGGGGGGG          OOOOOOOOOO        !!!!"
PLAY "o2l16b9n0baan0g-n0g-n0g-eeen0o1b9n0baan0b"
PRINT "GO!!!!!"
PLAY "T160O0L32EFGEFDC"
PRINT "GO!!!!!"
PLAY "T160O0L32EFGEFDC"
PRINT "GO!!!!!"
PLAY "T160O0L32EFGEFDC"
PRINT "GO!!!!!"
PLAY "T160O0L32EFGEFDC"
PRINT "GO!!!!!"
PLAY "T160O0L32EFGEFDC"
PRINT "GO!!!!!"
PLAY "T160O0L32EFGEFDC"
SLEEP 1
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
SLEEP 1
NEXT X
PRINT "                                   Thank You!"
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT
PRINT

